

name: Continuos Integration


on:
  push:
    branches:
      -main

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.
      
      - name: run install, build and test
        run: |
          npm install
          npm run test
          npm run build
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: ./build

      - name: Deploy to Test Enviroment
        uses: test-deploy-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        if: ${{success() }}

      - name: Send failure email notification
         if: failure()
         run: |
           curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"to":"tiagocosta225@gmail.com", "subject":"CI/CD Pipeline Failed", "body":"Your CI/CD pipeline has failed. Please check the logs for more information."}' \
            https://api.sendgrid.com/v3/mail/send  # Substitua pelo serviço de e-mail de sua escolha
