name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x  

      # Passo 2: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Passo 3: Executar testes unitários
      - name: Run unit tests
        run: npm test

      # Passo 4: Construir a aplicação
      - name: Build application
        run: npm run build

      - name: List files after build
        run: ls -lh

      - name: Zip build directory
        run: |
          if [ -d "./build" ]; then
            zip -r build.zip ./build
            chmod 777 build.zip  
          else
            echo "Error: ./build directory not found!"
          exit 1
          fi  

      - name: List files
        run: ls -lh

      - name: Upload the artifact
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: path/to/my/artifact.tar.gz

# ... next job or whenever you need the artifact

      - name: Download the artifact
        uses: actions/download-artifact@v1
        with:
          name: my-artifact
          path: ./

      - name: Upload the release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifact.tar.gz
          asset_name: artifact.tar.gz
          asset_content_type: application/gzip
        
  deploy-to-test:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: test-environment
    steps:
      # Passo 8: Fazer deploy no ambiente de teste
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Test Environment
        run: echo "Deploying to test environment..."
        # Aqui você pode adicionar os comandos específicos para fazer o deploy
        # Exemplo: usar `scp`, `rsync`, ou uma ação específica de deploy (como para AWS, Heroku, etc.)

  notify-on-failure:
    if: failure()
    runs-on: ubuntu-latest
    needs: [build-and-test, deploy-to-test]
    steps:
      # Passo 9: Notificar o desenvolvedor por e-mail em caso de falha
      - name: Send failure email notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"to":"tiagocosta225@gmail.com", "subject":"CI/CD Pipeline Failed", "body":"Your CI/CD pipeline has failed. Please check the logs for more information."}' \
            https://api.sendgrid.com/v3/mail/send  # Substitua pelo serviço de e-mail de sua escolha
